# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'jphack_b2110' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  # Pods for jphack_b2110

end
